name=DHT11_Lite
version=1.0.0
author=Sirio Guy <lu3alt@gmail.com>
maintainer=Sirio Guy <lu3alt@gmail.com>
sentence=Lightweight, non-blocking DHT11 driver for AVR-based Arduino boards.
paragraph=It uses direct port manipulation and a state machine leaving the Arduino completely free.
category=Sensors
url=https://github.com/SirioGuy/DHT11_Lite
architectures=avr
depends=